# Contador
## Desafio bootcamp Santander 2023

Consiste no desenvolvimento de um fluxo de c√≥digo que recebe dois n√∫meros, onde o segundo input deve ser maior que o primeiro.

Para tal √© feito a cria√ß√£o de uma Exception personalizada. 

###  √â necessario utilizar de extends da classe Exception/UnchekedException na classe que ser√° o nossa Exce√ß√£o, onde:

Exception s√£o os erros recuper√°veis

UnchekedException s√£o erros n√£o recuper√°veis

Exemplo de c√≥digo utilizado para captura e tratamento de erros em java:

```java
//try "tenta" executar o bloco de c√≥digo, caso encontre determinado erro direciona para o bloco catch
try {
    // seu c√≥digo

//catch "captura" o erro passado por par√¢metro para trata-lo dentro do bloco de c√≥digo do mesmo.
} catch (<nome da exce√ß√£o> e) {

//finally √© executado independente da execu√ß√£o acima.
//desde que o programa n√£o seja encerrado devido a uma uncheked
} finally {
    //seu c√≥digo
}
```
#### üìö Palavras-chave Throw e Throws

##### Breve explica√ß√£o:
Imagine nossos blocos de c√≥digo como caixas, e dentro destas caixas possuimos outras caixas.
Quando utilizamos throw estamos falando que a responsabilidade de abrir aquela caixa est√° sendo "jogada pra cima", de maneira que a caixa que est√° acima tem de resolver o que est√° ali ou ela tamb√©m pode "jogar para cima" a responsabilidade.

J√° na utiliza√ß√£o de throws √© diferente estamos dizendo para determinada caixa: "A responsabilidade √© sua, resolve ai".

Lembre-se que estamos falando de tratativas de erros. Abra√ßos.

